/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "both",
                centerStage: "both",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'Symbol_Rocket',
                            symbolName: 'Symbol_Rocket',
                            type: 'rect',
                            rect: ['-80', '556', '799', '521', 'auto', 'auto']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '640px', '960px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,0.00)"]
                        }
                    }
                },
                timeline: {
                    duration: 3333,
                    autoPlay: true,
                    data: [
                        [
                            "eid715",
                            "background-color",
                            0,
                            0,
                            "linear",
                            "${Stage}",
                            'rgba(255,255,255,0.00)',
                            'rgba(255,255,255,0.00)'
                        ]
                    ]
                }
            },
            "Symbol_Rocket": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            rect: ['46.5%', '-200.4%', '5.6%', '8.1%', 'auto', 'auto'],
                            id: 'rocket2',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket2.png', '0px', '0px']
                        },
                        {
                            rect: ['48.7%', '92.8%', '8.3%', '7.2%', 'auto', 'auto'],
                            id: 'rocket3',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket3.png', '0px', '0px']
                        },
                        {
                            rect: ['38.4%', '-179.5%', '8.3%', '8.7%', 'auto', 'auto'],
                            id: 'rocket4',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket4.png', '0px', '0px']
                        },
                        {
                            rect: ['34.9%', '80.3%', '5.5%', '8.7%', 'auto', 'auto'],
                            id: 'rocket5',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket5.png', '0px', '0px']
                        },
                        {
                            rect: ['45.7%', '-192.4%', '7.4%', '12%', 'auto', 'auto'],
                            id: 'rocket6',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket6.png', '0px', '0px']
                        },
                        {
                            rect: ['52.2%', '-179.5%', '8.2%', '8.7%', 'auto', 'auto'],
                            id: 'rocket7',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket7.png', '0px', '0px']
                        },
                        {
                            rect: ['66.5%', '-168.1%', '5.5%', '8.7%', 'auto', 'auto'],
                            id: 'rocket8',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket8.png', '0px', '0px']
                        },
                        {
                            rect: ['46.8%', '15.8%', '6.4%', '10%', 'auto', 'auto'],
                            id: 'rocket12',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket12.png', '0px', '0px']
                        },
                        {
                            rect: ['47.3%', '-152.4%', '5.4%', '40.7%', 'auto', 'auto'],
                            overflow: 'hidden',
                            id: 'rocket9',
                            opacity: '0',
                            type: 'image',
                            fill: ['rgba(0,0,0,0)', 'images/rocket9.png', '0%', '0%']
                        }
                    ],
                    style: {
                        '${symbolSelector}': {
                            rect: [null, null, '799px', '521px']
                        }
                    }
                },
                timeline: {
                    duration: 3333,
                    autoPlay: true,
                    data: [
                        [
                            "eid299",
                            "top",
                            1333,
                            333,
                            "linear",
                            "${rocket4}",
                            '27.64%',
                            '19.77%'
                        ],
                        [
                            "eid624",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket4}",
                            '19.77%',
                            '19.77%'
                        ],
                        [
                            "eid682",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket4}",
                            '19.77%',
                            '-179.5%'
                        ],
                        [
                            "eid306",
                            "left",
                            1666,
                            200,
                            "linear",
                            "${rocket3}",
                            '48.68%',
                            '45.93%'
                        ],
                        [
                            "eid626",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket3}",
                            '45.93%',
                            '45.93%'
                        ],
                        [
                            "eid669",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket3}",
                            '45.93%',
                            '45.93%'
                        ],
                        [
                            "eid468",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket5}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid622",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket5}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid659",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket5}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid694",
                            "left",
                            0,
                            0,
                            "linear",
                            "${rocket12}",
                            '46.81%',
                            '46.81%'
                        ],
                        [
                            "eid707",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket12}",
                            '46.81%',
                            '46.81%'
                        ],
                        [
                            "eid712",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket12}",
                            '46.81%',
                            '46.81%'
                        ],
                        [
                            "eid313",
                            "background-position",
                            2066,
                            0,
                            "linear",
                            "${rocket8}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid537",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket8}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid652",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket8}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid466",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket8}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid613",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket8}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid651",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket8}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid469",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket3}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid627",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket3}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid671",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket3}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid327",
                            "opacity",
                            2266,
                            60,
                            "linear",
                            "${rocket9}",
                            '0',
                            '0.30894278656176'
                        ],
                        [
                            "eid328",
                            "opacity",
                            2326,
                            60,
                            "linear",
                            "${rocket9}",
                            '0.30894278656176',
                            '0'
                        ],
                        [
                            "eid330",
                            "opacity",
                            2385,
                            81,
                            "linear",
                            "${rocket9}",
                            '0',
                            '0.33774302911952'
                        ],
                        [
                            "eid686",
                            "opacity",
                            2466,
                            37,
                            "linear",
                            "${rocket9}",
                            '0.33774302911952',
                            '0.19512195121951'
                        ],
                        [
                            "eid332",
                            "opacity",
                            2503,
                            296,
                            "linear",
                            "${rocket9}",
                            '0.19512200355529785',
                            '1'
                        ],
                        [
                            "eid607",
                            "opacity",
                            3066,
                            0,
                            "linear",
                            "${rocket9}",
                            '1',
                            '1'
                        ],
                        [
                            "eid645",
                            "opacity",
                            3133,
                            0,
                            "linear",
                            "${rocket9}",
                            '1',
                            '1'
                        ],
                        [
                            "eid290",
                            "left",
                            1199,
                            134,
                            "linear",
                            "${rocket2}",
                            '3.63%',
                            '47.19%'
                        ],
                        [
                            "eid629",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket2}",
                            '47.19%',
                            '47.19%'
                        ],
                        [
                            "eid673",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket2}",
                            '47.19%',
                            '47.19%'
                        ],
                        [
                            "eid470",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket4}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid625",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket4}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid667",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket4}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid472",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket6}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid619",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket6}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid664",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket6}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid281",
                            "left",
                            533,
                            333,
                            "linear",
                            "${rocket6}",
                            '90.49%',
                            '46.3%'
                        ],
                        [
                            "eid617",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket6}",
                            '46.3%',
                            '46.3%'
                        ],
                        [
                            "eid663",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket6}",
                            '46.3%',
                            '46.3%'
                        ],
                        [
                            "eid322",
                            "left",
                            2266,
                            0,
                            "linear",
                            "${rocket9}",
                            '47.31%',
                            '47.31%'
                        ],
                        [
                            "eid710",
                            "left",
                            3066,
                            67,
                            "linear",
                            "${rocket9}",
                            '47.31%',
                            '47.34%'
                        ],
                        [
                            "eid292",
                            "background-position",
                            1333,
                            0,
                            "linear",
                            "${rocket7}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid538",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket7}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid656",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket7}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid536",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket12}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid648",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket12}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid318",
                            "background-position",
                            2266,
                            0,
                            "linear",
                            "${rocket9}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid329",
                            "background-position",
                            2503,
                            0,
                            "linear",
                            "${rocket9}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid331",
                            "background-position",
                            2622,
                            0,
                            "linear",
                            "${rocket9}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid535",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket9}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid647",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket9}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@% @@1@@%'}
                        ],
                        [
                            "eid291",
                            "top",
                            1199,
                            134,
                            "linear",
                            "${rocket2}",
                            '0%',
                            '-1.16%'
                        ],
                        [
                            "eid630",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket2}",
                            '-1.16%',
                            '-1.16%'
                        ],
                        [
                            "eid677",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket2}",
                            '-1.16%',
                            '-200.41%'
                        ],
                        [
                            "eid695",
                            "top",
                            0,
                            0,
                            "linear",
                            "${rocket12}",
                            '15.74%',
                            '15.74%'
                        ],
                        [
                            "eid685",
                            "top",
                            3066,
                            67,
                            "linear",
                            "${rocket12}",
                            '15.74%',
                            '15.81%'
                        ],
                        [
                            "eid713",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket12}",
                            '15.81%',
                            '-183.53%'
                        ],
                        [
                            "eid300",
                            "top",
                            1333,
                            333,
                            "linear",
                            "${rocket7}",
                            '30.13%',
                            '19.77%'
                        ],
                        [
                            "eid615",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket7}",
                            '19.77%',
                            '19.77%'
                        ],
                        [
                            "eid683",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket7}",
                            '19.77%',
                            '-179.5%'
                        ],
                        [
                            "eid467",
                            "skewY",
                            2799,
                            0,
                            "linear",
                            "${rocket9}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid610",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket9}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid646",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket9}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid283",
                            "background-position",
                            1199,
                            0,
                            "linear",
                            "${rocket2}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid543",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket2}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid676",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket2}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid465",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket2}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid642",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket2}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid675",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket2}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid699",
                            "top",
                            1666,
                            400,
                            "linear",
                            "${rocket8}",
                            '82.16%',
                            '77.55%'
                        ],
                        [
                            "eid317",
                            "top",
                            2066,
                            200,
                            "linear",
                            "${rocket8}",
                            '77.55%',
                            '32.82%'
                        ],
                        [
                            "eid612",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket8}",
                            '32.82%',
                            '32.82%'
                        ],
                        [
                            "eid678",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket8}",
                            '32.82%',
                            '-168.11%'
                        ],
                        [
                            "eid308",
                            "background-position",
                            1866,
                            0,
                            "linear",
                            "${rocket5}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid540",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket5}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid660",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket5}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid698",
                            "left",
                            1666,
                            400,
                            "linear",
                            "${rocket8}",
                            '66.46%',
                            '50.94%'
                        ],
                        [
                            "eid611",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket8}",
                            '50.94%',
                            '50.94%'
                        ],
                        [
                            "eid649",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket8}",
                            '50.94%',
                            '50.94%'
                        ],
                        [
                            "eid301",
                            "left",
                            1333,
                            333,
                            "linear",
                            "${rocket7}",
                            '91.87%',
                            '52.82%'
                        ],
                        [
                            "eid614",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket7}",
                            '52.82%',
                            '52.82%'
                        ],
                        [
                            "eid653",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket7}",
                            '52.82%',
                            '52.82%'
                        ],
                        [
                            "eid282",
                            "top",
                            533,
                            333,
                            "linear",
                            "${rocket6}",
                            '5.75%',
                            '6.91%'
                        ],
                        [
                            "eid618",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket6}",
                            '6.91%',
                            '6.91%'
                        ],
                        [
                            "eid684",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket6}",
                            '6.91%',
                            '-192.36%'
                        ],
                        [
                            "eid307",
                            "top",
                            1666,
                            200,
                            "linear",
                            "${rocket3}",
                            '92.9%',
                            '25.73%'
                        ],
                        [
                            "eid628",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket3}",
                            '25.73%',
                            '25.73%'
                        ],
                        [
                            "eid681",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket3}",
                            '25.73%',
                            '-173.54%'
                        ],
                        [
                            "eid302",
                            "background-position",
                            1666,
                            0,
                            "linear",
                            "${rocket3}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid542",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket3}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid672",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket3}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid697",
                            "top",
                            1666,
                            200,
                            "linear",
                            "${rocket5}",
                            '80.24%',
                            '77.55%'
                        ],
                        [
                            "eid311",
                            "top",
                            1866,
                            200,
                            "linear",
                            "${rocket5}",
                            '77.55%',
                            '32.82%'
                        ],
                        [
                            "eid621",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket5}",
                            '32.82%',
                            '32.82%'
                        ],
                        [
                            "eid680",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket5}",
                            '32.82%',
                            '-166.45%'
                        ],
                        [
                            "eid471",
                            "skewY",
                            2866,
                            0,
                            "linear",
                            "${rocket7}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid616",
                            "skewY",
                            3066,
                            0,
                            "linear",
                            "${rocket7}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid655",
                            "skewY",
                            3133,
                            0,
                            "linear",
                            "${rocket7}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid276",
                            "background-position",
                            533,
                            0,
                            "linear",
                            "${rocket6}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid539",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket6}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid661",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket6}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid298",
                            "left",
                            1333,
                            333,
                            "linear",
                            "${rocket4}",
                            '0%',
                            '39.05%'
                        ],
                        [
                            "eid623",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket4}",
                            '39.05%',
                            '39.05%'
                        ],
                        [
                            "eid665",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket4}",
                            '39.05%',
                            '39.05%'
                        ],
                        [
                            "eid293",
                            "background-position",
                            1333,
                            0,
                            "linear",
                            "${rocket4}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid541",
                            "background-position",
                            3066,
                            0,
                            "linear",
                            "${rocket4}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid668",
                            "background-position",
                            3133,
                            0,
                            "linear",
                            "${rocket4}",
                            [0,0],
                            [0,0],
                            {valueTemplate: '@@0@@px @@1@@px'}
                        ],
                        [
                            "eid323",
                            "top",
                            2266,
                            0,
                            "linear",
                            "${rocket9}",
                            '46.26%',
                            '46.26%'
                        ],
                        [
                            "eid608",
                            "top",
                            3066,
                            0,
                            "linear",
                            "${rocket9}",
                            '46.26%',
                            '46.26%'
                        ],
                        [
                            "eid679",
                            "top",
                            3104,
                            29,
                            "linear",
                            "${rocket9}",
                            '46.26%',
                            '46.22%'
                        ],
                        [
                            "eid711",
                            "top",
                            3133,
                            200,
                            "linear",
                            "${rocket9}",
                            '46.22%',
                            '-152.44%'
                        ],
                        [
                            "eid696",
                            "left",
                            1666,
                            200,
                            "linear",
                            "${rocket5}",
                            '34.92%',
                            '41.8%'
                        ],
                        [
                            "eid312",
                            "left",
                            1866,
                            200,
                            "linear",
                            "${rocket5}",
                            '41.8%',
                            '43.56%'
                        ],
                        [
                            "eid620",
                            "left",
                            3066,
                            0,
                            "linear",
                            "${rocket5}",
                            '43.56%',
                            '43.56%'
                        ],
                        [
                            "eid657",
                            "left",
                            3133,
                            0,
                            "linear",
                            "${rocket5}",
                            '43.56%',
                            '43.56%'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("rocket_edgeActions.js");
})("Page_Rocket");
